# Generated by Django 4.2.8 on 2024-01-26 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_alter_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('name', models.CharField(max_length=250, null=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'role',
                'ordering': ['updated'],
            },
        ),
        migrations.CreateModel(
            name='RoleUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('role', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='roleuser_role', to='management.role')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roleuser_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'role_user',
                'ordering': ['updated'],
            },
        ),
    ]
