# Generated by Django 4.2.8 on 2024-01-26 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_role_roleuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roleuser',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roleuser_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
