# Generated by Django 4.2.8 on 2024-01-26 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_alter_roleuser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roleuser',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='roleuser_role', to='management.role'),
        ),
    ]
